-- require('lualine').setup({
--     options = {
--         theme = "gruvbox",
--         -- ... the rest of your lualine config
--         -- section_separators = { left = '', right = '' },
--         -- component_separators = { left = '', right = '' }
--     }
-- })
